INSERT INTO market_instrument (symbol, company_name, asset_type, market, currency, enabled, sort_order) VALUES
('AAPL', 'Apple Inc.', 'STOCK', 'US', 'USD', 1, 1),
('MSFT', 'Microsoft Corporation', 'STOCK', 'US', 'USD', 1, 2),
('NVDA', 'NVIDIA Corporation', 'STOCK', 'US', 'USD', 1, 3),
('AMZN', 'Amazon.com, Inc.', 'STOCK', 'US', 'USD', 1, 4),
('TSLA', 'Tesla, Inc.', 'STOCK', 'US', 'USD', 1, 5),
('GOOGL', 'Alphabet Inc.', 'STOCK', 'US', 'USD', 1, 6),
('META', 'Meta Platforms, Inc.', 'STOCK', 'US', 'USD', 1, 7),
('0700.HK', 'Tencent Holdings Limited', 'STOCK', 'HK', 'HKD', 1, 8),
('9988.HK', 'Alibaba Group Holding Limited', 'STOCK', 'HK', 'HKD', 1, 9),
('9618.HK', 'JD.com, Inc.', 'STOCK', 'HK', 'HKD', 1, 10),
('600519.SS', 'Kweichow Moutai Co., Ltd.', 'STOCK', 'CN', 'CNY', 1, 11),
('000001.SZ', 'Ping An Bank Co., Ltd.', 'STOCK', 'CN', 'CNY', 1, 12),
('300750.SZ', 'Contemporary Amperex Technology Co., Limited', 'STOCK', 'CN', 'CNY', 1, 13),
('601318.SS', 'Ping An Insurance (Group) Company of China, Ltd.', 'STOCK', 'CN', 'CNY', 1, 14),
('AGG', 'iShares Core U.S. Aggregate Bond ETF', 'BOND', 'US', 'USD', 1, 101),
('BND', 'Vanguard Total Bond Market ETF', 'BOND', 'US', 'USD', 1, 102),
('LQD', 'iShares iBoxx $ Investment Grade Corporate Bond ETF', 'BOND', 'US', 'USD', 1, 103),
('TLT', 'iShares 20+ Year Treasury Bond ETF', 'BOND', 'US', 'USD', 1, 104),
('IEF', 'iShares 7-10 Year Treasury Bond ETF', 'BOND', 'US', 'USD', 1, 105),
('HYG', 'iShares iBoxx $ High Yield Corporate Bond ETF', 'BOND', 'US', 'USD', 1, 106),
('511010.SS', 'SSE Government Bond ETF', 'BOND', 'CN', 'CNY', 1, 107),
('511220.SS', 'SSE Corporate Bond ETF', 'BOND', 'CN', 'CNY', 1, 108),
('2821.HK', 'iShares Core Hong Kong Bond ETF', 'BOND', 'HK', 'HKD', 1, 109);
