DELETE FROM market_instrument;

INSERT INTO market_instrument (symbol, company_name, asset_type, market, currency, enabled, sort_order) VALUES
('AAPL', 'Apple Inc.', 'STOCK', 'US', 'USD', 1, 1),
('MSFT', 'Microsoft Corporation', 'STOCK', 'US', 'USD', 1, 2),
('NVDA', 'NVIDIA Corporation', 'STOCK', 'US', 'USD', 1, 3),
('AMZN', 'Amazon.com, Inc.', 'STOCK', 'US', 'USD', 1, 4),
('TSLA', 'Tesla, Inc.', 'STOCK', 'US', 'USD', 1, 5),
('GOOGL', 'Alphabet Inc.', 'STOCK', 'US', 'USD', 1, 6),
('META', 'Meta Platforms, Inc.', 'STOCK', 'US', 'USD', 1, 7),
('BRK.B', 'Berkshire Hathaway Inc.', 'STOCK', 'US', 'USD', 1, 8),
('JPM', 'JPMorgan Chase & Co.', 'STOCK', 'US', 'USD', 1, 9),
('UNH', 'UnitedHealth Group Incorporated', 'STOCK', 'US', 'USD', 1, 10),
('V', 'Visa Inc.', 'STOCK', 'US', 'USD', 1, 11),
('MA', 'Mastercard Incorporated', 'STOCK', 'US', 'USD', 1, 12),
('PG', 'Procter & Gamble Company', 'STOCK', 'US', 'USD', 1, 13),
('JNJ', 'Johnson & Johnson', 'STOCK', 'US', 'USD', 1, 14),
('XOM', 'Exxon Mobil Corporation', 'STOCK', 'US', 'USD', 1, 15),
('AVGO', 'Broadcom Inc.', 'STOCK', 'US', 'USD', 1, 16),
('ORCL', 'Oracle Corporation', 'STOCK', 'US', 'USD', 1, 17),
('COST', 'Costco Wholesale Corporation', 'STOCK', 'US', 'USD', 1, 18),
('KO', 'The Coca-Cola Company', 'STOCK', 'US', 'USD', 1, 19),
('PEP', 'PepsiCo, Inc.', 'STOCK', 'US', 'USD', 1, 20),
('BABA', 'Alibaba Group Holding Limited (ADR)', 'STOCK', 'CN', 'USD', 1, 21),
('JD', 'JD.com, Inc. (ADR)', 'STOCK', 'CN', 'USD', 1, 22),
('PDD', 'PDD Holdings Inc. (ADR)', 'STOCK', 'CN', 'USD', 1, 23),
('BIDU', 'Baidu, Inc. (ADR)', 'STOCK', 'CN', 'USD', 1, 24),
('TCEHY', 'Tencent Holdings Limited (ADR)', 'STOCK', 'HK', 'USD', 1, 25),
('NTES', 'NetEase, Inc. (ADR)', 'STOCK', 'CN', 'USD', 1, 26),
('NIO', 'NIO Inc. (ADR)', 'STOCK', 'CN', 'USD', 1, 27),
('XPEV', 'XPeng Inc. (ADR)', 'STOCK', 'CN', 'USD', 1, 28),
('LI', 'Li Auto Inc. (ADR)', 'STOCK', 'CN', 'USD', 1, 29),
('HSBC', 'HSBC Holdings plc', 'STOCK', 'HK', 'USD', 1, 30),
('AGG', 'iShares Core U.S. Aggregate Bond ETF', 'BOND', 'US', 'USD', 1, 101),
('BND', 'Vanguard Total Bond Market ETF', 'BOND', 'US', 'USD', 1, 102),
('LQD', 'iShares iBoxx $ Investment Grade Corporate Bond ETF', 'BOND', 'US', 'USD', 1, 103),
('TLT', 'iShares 20+ Year Treasury Bond ETF', 'BOND', 'US', 'USD', 1, 104),
('IEF', 'iShares 7-10 Year Treasury Bond ETF', 'BOND', 'US', 'USD', 1, 105),
('SHY', 'iShares 1-3 Year Treasury Bond ETF', 'BOND', 'US', 'USD', 1, 106),
('GOVT', 'iShares U.S. Treasury Bond ETF', 'BOND', 'US', 'USD', 1, 107),
('BIL', 'SPDR Bloomberg 1-3 Month T-Bill ETF', 'BOND', 'US', 'USD', 1, 108),
('TIP', 'iShares TIPS Bond ETF', 'BOND', 'US', 'USD', 1, 109),
('MUB', 'iShares National Muni Bond ETF', 'BOND', 'US', 'USD', 1, 110),
('HYG', 'iShares iBoxx $ High Yield Corporate Bond ETF', 'BOND', 'US', 'USD', 1, 111),
('EMB', 'iShares J.P. Morgan USD Emerging Markets Bond ETF', 'BOND', 'US', 'USD', 1, 112),
('BWX', 'SPDR Bloomberg International Treasury Bond ETF', 'BOND', 'US', 'USD', 1, 113),
('VCIT', 'Vanguard Intermediate-Term Corporate Bond ETF', 'BOND', 'US', 'USD', 1, 114),
('VCLT', 'Vanguard Long-Term Corporate Bond ETF', 'BOND', 'US', 'USD', 1, 115),
('IGSB', 'iShares Short-Term Corporate Bond ETF', 'BOND', 'US', 'USD', 1, 116),
('SPSB', 'SPDR Portfolio Short Term Corporate Bond ETF', 'BOND', 'US', 'USD', 1, 117),
('BSV', 'Vanguard Short-Term Bond ETF', 'BOND', 'US', 'USD', 1, 118),
('BIV', 'Vanguard Intermediate-Term Bond ETF', 'BOND', 'US', 'USD', 1, 119),
('BLV', 'Vanguard Long-Term Bond ETF', 'BOND', 'US', 'USD', 1, 120);
